language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

before_install:
  - openssl aes-256-cbc -K $encrypted_79af4426a6d5_key -iv $encrypted_79af4426a6d5_iv -in key.json.enc -out key.json -d

services:
  - docker