language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

before_install:
  - chmod +x gradlew
  - openssl aes-256-cbc -K $encrypted_8af46ad501b7_key -iv $encrypted_8af46ad501b7_iv -in key.json.enc -out key.json -d

services:
  - docker