#version: 2
#jobs:
#  build:
#    docker:
#      - image: circleci/openjdk:8-jdk
#
#    working_directory: ~/apigateway-soa-project
#
#    environment:
#      JVM_OPTS: -Xmx3200m
#      TERM: dumb
#
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "build.gradle" }}
#            - v1-dependencies-
#
#      - run: gradle dependencies
#      - save_cache:
#          paths:
#            - ~/.gradle
#          key: v1-dependencies-{{ checksum "build.gradle" }}
#      - run: gradle test


version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run : |
          echo $GCLOUD_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${PROJECT_ID}
          gcloud auth configure-docker
      - run : |
          docker build -t asia.gcr.io/soa-group-7-174/api-gateway:$CIRCLE_BUILD_NUM .
          docker push asia.gcr.io/soa-group-7-174/api-gateway:$CIRCLE_BUILD_NUM